name: CI Pipeline

on:
  push:

jobs:
  check_working_repo:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Train Model
      run: |
        python train.py

    - name: Test Model
      run: |
        python test.py